### PR TITLE
[poincare] Power: when reducing, apply multinome development only when the target is the User

### LINKED ISSUE #1059: Error in the graph of a function.
#### Describe the bug
Error in the graph of a function. The function should be smoothly decreasing to 0, but it oscillates like a Runge's phenomenon.

#### Screenshots
screenshot

#### To Reproduce
1. Go to the 'Function.' app
2. Type `binomial(20,8)*(x^8)*(1-x)^12`
3. Go to Graph

#### Expected behavior
Screenshot 2019-08-30 at 16 29 12

#### Environment
 - Epsilon version 11.2.0
 - Simulator, Android app and actual device

### PR DESCRIPTION
**Pull request by EmilieNumworks**
Fixes #1059

### CODE REVIEW

File: poincare/src/equal.cpp [hunk 1]
```diff
@@ -46,7 +46,11 @@ Evaluation<T> EqualNode::templatedApproximate(Context * context, Preferences::Co
 
 Expression Equal::standardEquation(Context * context, Preferences::ComplexFormat complexFormat, Preferences::AngleUnit angleUnit) const {
   Expression sub = Subtraction::Builder(childAtIndex(0).clone(), childAtIndex(1).clone());
-  return sub.reduce(context, complexFormat, angleUnit);
+  /* When reducing the equation, we specify the reduction target to be
+   * SystemForAnalysis. This enables to expand Newton multinom to be able to
+   * detect polynom correctly ("(x=2)^2" in this form won't be detected
```
Comment (LeaNumworks) [inline poincare/src/equal.cpp]: (x+2)^2 is a better example

File: poincare/src/power.cpp [hunk 2]
```diff
@@ -871,12 +871,12 @@ Expression Power::shallowBeautify(ExpressionNode::ReductionContext reductionCont
     return result;
   }
 
-  /* Optional Step 3: if the ReductionTarget is the System, turn a^(p/q) into
-   * (root(a, q))^p
+  /* Optional Step 3: if the ReductionTarget is the SystemForApproximation,
```
Comment (LeaNumworks) [inline poincare/src/power.cpp]: SystemForAnalysis and SystemForApproximation
